// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3jkqEoJvMlz-27ozU0xanD2CPPCFG8DI',
    appId: '1:839987922474:web:cc5601c009d036e028e553',
    messagingSenderId: '839987922474',
    projectId: 'login-demo-prjk',
    authDomain: 'login-demo-prjk.firebaseapp.com',
    storageBucket: 'login-demo-prjk.firebasestorage.app',
    measurementId: 'G-M3FR6D29LR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTeKXLjX_hQPeYN0SJpL7MDzZbRdUiGM',
    appId: '1:839987922474:android:10a8d70b9803526028e553',
    messagingSenderId: '839987922474',
    projectId: 'login-demo-prjk',
    storageBucket: 'login-demo-prjk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3jkqEoJvMlz-27ozU0xanD2CPPCFG8DI',
    appId: '1:839987922474:web:0d344e5ed78814bf28e553',
    messagingSenderId: '839987922474',
    projectId: 'login-demo-prjk',
    authDomain: 'login-demo-prjk.firebaseapp.com',
    storageBucket: 'login-demo-prjk.firebasestorage.app',
    measurementId: 'G-3RMWNLP6PJ',
  );
}
